services:
  # =====================================================
  # DATABASE SERVICES
  # =====================================================
  
  # IAM Service Database (PostgreSQL)
  iam-db:
    image: postgres:15
    container_name: ecomovil-iam-db
    environment:
      POSTGRES_DB: ecomovil_iam_db
      POSTGRES_USER: iam_user
      POSTGRES_PASSWORD: iam_password
    ports:
      - "5433:5432"
    volumes:
      - iam_data:/var/lib/postgresql/data
    networks:
      - ecomovil-network

  # Plans Service Database (MySQL)
  plans-db:
    image: mysql:8.0
    container_name: ecomovil-plans-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecomovil_plans_db
      MYSQL_USER: plans_user
      MYSQL_PASSWORD: plans_password
    ports:
      - "3306:3306"
    volumes:
      - plans_data:/var/lib/mysql
    networks:
      - ecomovil-network

  # Users Service Database (MySQL)
  users-db:
    image: mysql:8.0
    container_name: ecomovil-users-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecomovil_users_db
      MYSQL_USER: users_user
      MYSQL_PASSWORD: users_password
    ports:
      - "3307:3306"
    volumes:
      - users_data:/var/lib/mysql
    networks:
      - ecomovil-network

  # =====================================================
  # MICROSERVICES
  # =====================================================

  # IAM Service
  iam-service:
    build: 
      context: ./iam
      dockerfile: Dockerfile
    container_name: ecomovil-iam-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://iam-db:5432/ecomovil_iam_db
      SPRING_DATASOURCE_USERNAME: iam_user
      SPRING_DATASOURCE_PASSWORD: iam_password
      SERVER_PORT: 8080
      AUTHORIZATION_JWT_SECRET: mySecretKeyThatIsLongEnoughForJWTHMACAlgorithmRequirements1234567890
    ports:
      - "8080:8080"
    depends_on:
      - iam-db
    networks:
      - ecomovil-network
    restart: unless-stopped

  # Plans Service
  plans-service:
    build: 
      context: ./plans/untitled
      dockerfile: Dockerfile
    container_name: ecomovil-plans-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://plans-db:3306/ecomovil_plans_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: plans_user
      SPRING_DATASOURCE_PASSWORD: plans_password
      SERVER_PORT: 8081
      AUTHORIZATION_JWT_SECRET: mySecretKeyThatIsLongEnoughForJWTHMACAlgorithmRequirements1234567890
    ports:
      - "8081:8081"
    depends_on:
      - plans-db
    networks:
      - ecomovil-network
    restart: unless-stopped

  # Users Service
  users-service:
    build: 
      context: ./users
      dockerfile: Dockerfile
    container_name: ecomovil-users-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://users-db:3306/ecomovil_users_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: users_user
      SPRING_DATASOURCE_PASSWORD: users_password
      SERVER_PORT: 8082
      AUTHORIZATION_JWT_SECRET: mySecretKeyThatIsLongEnoughForJWTHMACAlgorithmRequirements1234567890
      SERVICES_PLANS_URL: http://plans-service:8081
    ports:
      - "8082:8082"
    depends_on:
      - users-db
      - plans-service
    networks:
      - ecomovil-network
    restart: unless-stopped

volumes:
  iam_data:
    driver: local
  plans_data:
    driver: local
  users_data:
    driver: local

networks:
  ecomovil-network:
    driver: bridge
